exclude: "docs|node_modules|migrations|.git|.tox"
default_stages: [ pre-commit ]
fail_fast: true
default_language_version:
  python: python3

repos:
  - repo: https://github.com/rtts/djhtml
    rev: 3.0.7
    hooks:
      - id: djhtml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: local
    hooks:
      - id: pretty-quick
        types_or: [ css, javascript ]
        name: Run pretty-quick from web/
        entry: bash -c "cd web && npx pretty-quick --staged"
        language: system
